-- V27: Huddle 语音、自动化规则、LDAP 同步、统一搜索
--
-- ⚠️  本文件已弃用。六张表的权威定义在 V28__platform_enhancement.sql 中。
--     V27__huddle_automation_ldap_search.sql 中的重复定义已删除，避免 Flyway 版本冲突。
--
-- 保留本文件作为占位迁移（空操作），确保 Flyway 版本号连续。
-- 如需新增表，请使用 V31+ 版本号。
--
-- 历史说明:
--   - im_huddle / im_huddle_participant → V28__platform_enhancement.sql（权威）
--   - automation_rule / automation_execution → V28__platform_enhancement.sql（权威）
--   - ldap_config / ldap_user_mapping → V28__platform_enhancement.sql（权威）
--   - unified_search_index → V28__platform_enhancement.sql（权威）
--   - im_huddle_signaling → 已删除（零代码使用，T7 重新设计）
